runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /favicon.ico
  static_files: /images/favicon.ico
  upload: /images/favicon.ico
#- url: /css
  #static_dir: css
- url: /images
  static_dir: images
- url: (/.*\..*)
  static_files: static\1
  upload: static(/.*\..*)
  application_readable: true
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: "1.6.1"
